[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_voting_system = "3psKCKAmTQEJ3idseY6tKs11JYN7BGoPuX6w7jqs1BAJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pradip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
